apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: game-editor-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: api
roleRef:
  kind: ClusterRole
  name: operator-game-editor-role
  apiGroup: rbac.authorization.k8s.io