appName: api
replicas: 1
port: 8080

ginMode: release

image:
  name: ghcr.io/austriandatalab/indiegamestream/api
  label: latest # Change to proper version tag
  pullPolicy: IfNotPresent

mysql:
  auth:
    database: api
    existingSecret: mysql-secret # Find proper way of handling authentication in production
  primary:
    containerPorts: 3306