appName: api
replicas: 1
port: 8080

image:
  name: ghcr.io/austriandatalab/indiegamestream/api
  label: latest # Change to proper version tag
  pullPolicy: IfNotPresent

env:
  ginMode: release
  mysqlDatabase: api
  mysqlRootUser: root
  mysqlHost: mysql.mysql.svc.cluster.local
  mysqlPort: 3306