appName: api
replicas: 1
port: 8080

image:
  name: ghcr.io/austriandatalab/indiegamestream/api
  label: v1.0.0 # Change to proper version tag
  pullPolicy: IfNotPresent

service:
  spec:
    loadBalancerClass: tailscale

env:
  ginMode: release
  mysqlDatabase: api
  mysqlRootUser: root
  mysqlHost: mysql.mysql.svc.cluster.local
  mysqlPort: 3306