apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: demo-dns-policy
spec:
  applyTo:
  - groups: [""]
    kinds: ["Service"]
    versions: ["v1"]
  match:
    scope: Namespaced | Cluster
    kinds:
    - apiGroups: ["*"]
      kinds: ["Service"]
    labelSelector:
      matchExpressions:
      - {key: "stunner.l7mp.io/owned-by", operator: "In", values: ["stunner"]}
  location: "spec.loadBalancerClass"
  parameters:
    assign:
      value: "tailscale"