apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: demo-dns-policy
spec:
  applyTo:
  - groups: [""]
    kinds: ["Service"]
    versions: ["v1"]
  match:
    scope: Cluster
    kinds:
    - apiGroups: ["*"]
      kinds: ["Service"]
  location: "spec[type:LoadBalancer].loadBalancerClass"
  parameters:
    assign:
      value: "tailscale"
    pathTests:
    - subPath: "spec.loadBalancerClass"
      condition: MustNotExist