---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - stream.indiegamestream.com
  resources:
  - games
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stream.indiegamestream.com
  resources:
  - games/finalizers
  verbs:
  - update
- apiGroups:
  - stream.indiegamestream.com
  resources:
  - games/status
  verbs:
  - get
  - patch
  - update
