# permissions for end users to view gatewayconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gatewayconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: gatewayconfig-viewer-role
rules:
- apiGroups:
  - stunner.indiegamestream.com
  resources:
  - gatewayconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stunner.indiegamestream.com
  resources:
  - gatewayconfigs/status
  verbs:
  - get
