{{- required ".Values.appConfig.production is required!" .Values.appConfig.production -}}
{{- required ".Values.appConfig.apiUrl is required!"  .Values.appConfig.apiUrl -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Values.appName }}
data:
  app.config.json: |-
{{ toJson .Values.appConfig | indent 4 }}