apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "frontend"
spec:
  type: LoadBalancer
  {{ if .Values.service.spec.loadBalancerClass }}
  loadBalancerClass: {{ .Values.service.spec.loadBalancerClass }}
  {{ end }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}