apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.image.name }}:{{ .Values.image.label }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.port }}
        volumeMounts:
        - name: "{{ .Values.appName }}-config-volume"
          mountPath: "{{ .Values.webRootDirectory }}/assets"
          readOnly: true
      volumes: 
      - name: "{{ .Values.appName }}-config-volume"
        configMap:
          name: "{{ .Values.appName }}-config"
          items:
          - key: app.config.json
            path: app.config.json