apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.image.name }}:{{ .Values.image.label }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.port }}
        env:
        - name: PORT
          value: {{ .Values.port | quote }}
        - name: GIN_MODE
          value: {{ .Values.env.ginMode | quote }}
        - name: MYSQL_DATABASE
          value: {{ .Values.env.mysqlDatabase | quote }}
        - name: MYSQL_ROOT_USER
          value: {{ .Values.env.mysqlRootUser | quote }}
        - name: MYSQL_ROOT_PASSWORD
          value: {{ required ".Values.env.mysqlRootPassword is required." .Values.env.mysqlRootPassword | quote }}
        - name: MYSQL_HOST
          value: {{ .Values.env.mysqlHost | quote }}
        - name: MYSQL_PORT
          value: {{ .Values.env.mysqlPort | quote }}
        - name: AZURE_TENANT_ID
          value: {{ required ".Values.env.azureTenantId is required." .Values.env.azureTenantId | quote }}
        - name: AZURE_CLIENT_ID
          value: {{ required ".Values.env.azureClientId is required." .Values.env.azureClientId | quote }}
        - name: AZURE_CLIENT_SECRET
          value: {{ required ".Values.env.azureClientSecret is required." .Values.env.azureClientSecret | quote }}
        - name: AZURE_STORAGE_ACCOUNT
          value: {{ required ".Values.env.azureStorageAccount is required." .Values.env.azureStorageAccount | quote }}
        - name: AZURE_CONTAINER_NAME
          value: {{ required ".Values.env.azureContainerName is required." .Values.env.azureContainerName | quote }}
        - name: AZURE_AKS_CLUSTER_NAME
          value: {{ required ".Values.env.azureAksClusterName is required." .Values.env.azureAksClusterName | quote }}
        - name: AZURERM_SUBSCRIPTION_ID
          value: {{ required ".Values.env.azurermSubscriptionId is required." .Values.env.azurermSubscriptionId | quote }}
        - name: AZURERM_RESOURCE_GROUP_NAME
          value: {{ required ".Values.env.azurermResourceGroupName is required." .Values.env.azurermResourceGroupName | quote }}