#The docker-compose is for local deployment.
services:
  mysql:
    env_file: .env.deployment
    image: 'mysql:8.4.0'
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ./internal/database:/bitnami/mysql/data
    networks:
      - api
    healthcheck:
      test: mysqladmin ping --host=${MYSQL_HOST} --port=${MYSQL_PORT} --user=${MYSQL_ROOT_USER} --password=${MYSQL_ROOT_PASSWORD}
    restart: on-failure
    #command: # fix from https://github.com/bitnami/containers/issues/44854#issuecomment-1800945882
    #  - "/opt/bitnami/mysql/bin/mysqld"
    #  - "--defaults-file=/opt/bitnami/mysql/conf/my.cnf"
    #  - "--basedir=/opt/bitnami/mysql"
    #  - "--datadir=/bitnami/mysql/data"
    #  - "--socket=/opt/bitnami/mysql/tmp/mysql.sock"
    #  - "--pid-file=/opt/bitnami/mysql/tmp/mysqld.pid"
  api:
    env_file: .env.deployment
    build: .
    ports:
      - "${PORT}:${PORT}"
    restart: on-failure
    networks:
      - api
    depends_on:
      mysql:
        condition: service_healthy

networks:
  api:
    driver: bridge