name: Build, test, scan and push images

on:
  push:
    branches:
      - develop
      - feature/aks-ci

  pull_request:
    branches:
      - develop
      - main

  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  NAMESPACE: austriandatalab
  SUB_NAMESPACE: indiegamestream
jobs:
  build-push-image:
    strategy:
      fail-fast: false
      matrix:
        image:
          # Add your images here (name of the component + directory that contains Dockerfile)
          - name: frontend
            directory: frontend
          - name: api
            directory: api
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    name: ${{ matrix.image.name }}

    steps:
      - uses: actions/checkout@v4

      - name: Check if test stage exists
        run: |
          if grep -q -i -E '^\s*FROM\s+[^\s]+\s+AS\s+test\s*$' ${{ matrix.image.directory }}/Dockerfile ; then
            echo "Test stage exists, continuing with tests."
            echo "test_stage_exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "Test stage does not exist, skipping tests."
            echo "test_stage_exists=false" >> "$GITHUB_OUTPUT"
          fi
        id: check_test_stage

      - name: Build Docker image to test stage
        if: steps.check_test_stage.outputs.test_stage_exists == 'true'
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ${{ matrix.image.directory }}
          file: ${{ matrix.image.directory }}/Dockerfile
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.SUB_NAMESPACE }}/${{ matrix.image.name }}-test:${{ github.sha }}
          target: test

      - name: Run test stage
        if: steps.check_test_stage.outputs.test_stage_exists == 'true'
        run: |
          docker run --rm ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.SUB_NAMESPACE }}/${{ matrix.image.name }}-test:${{ github.sha }}

      - name: Login to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.SUB_NAMESPACE }}/${{ matrix.image.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=match,pattern=\d.\d.\d.*
            type=sha

      - name: Build Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ${{ matrix.image.directory }}
          file: ${{ matrix.image.directory }}/Dockerfile
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.SUB_NAMESPACE }}/${{ matrix.image.name }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.SUB_NAMESPACE }}/${{ matrix.image.name }}:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          limit-severities-for-sarif: true
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ${{ matrix.image.directory }}
          file: ${{ matrix.image.directory }}/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.SUB_NAMESPACE }}/${{ matrix.image.name }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
          category: ${{ matrix.image.name }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Set WorkDir
        run: echo "##[set-output name=workdir;]${{ github.workspace }}/iac"

      - name: Login to Azure
        run: az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.AZURERM_TENANT_ID }}


      - name: Terraform Apply
        run: |
          cd ${{ github.workspace }}/iac
          export ARM_CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
          export ARM_CLIENT_ID=${{ secrets.CLIENT_ID }}
          export TF_VAR_subscription_id=${{ secrets.AZURERM_SUBSCRIPTION_ID }}
          export TF_VAR_tenant_id=${{ secrets.AZURERM_TENANT_ID }}
          export TF_VAR_tailscale_auth_key=${{secrets.TAILSCALE_AUTH_KEY}}
          export TF_VAR_tailscale_client_id=${{secrets.TAILSCALE_CLIENT_ID}}
          export TF_VAR_tailscale_client_secret=${{secrets.TAILSCALE_CLIENT_SECRET}}
          export TF_CLI_ARGS_init=" -backend-config=\"resource_group_name=${{ secrets.AZURERM_RESOURCE_GROUP_NAME }}\"  -backend-config=\"key=${{ secrets.KEY }}.tfstate\" -backend-config=\"storage_account_name=${{ secrets.AZURERM_STORAGE_ACCOUNT_NAME }}\"    -backend-config=\"container_name=tfbootstrapadmin\"   -backend-config=\"subscription_id=${{ secrets.AZURERM_SUBSCRIPTION_ID }}\"  -backend-config=\"tenant_id=${{ secrets.AZURERM_TENANT_ID }}\" "
          terraform init
          terraform plan -out=tfplan.bin -input=false
          terraform apply -auto-approve "tfplan.bin"
          az aks command invoke -n testCluster -g rg-service-not2day --command "helm repo add tailscale https://pkgs.tailscale.com/helmcharts && helm repo update && helm upgrade --install tailscale-operator tailscale/tailscale-operator --namespace=tailscale --create-namespace --set-string oauth.clientId=${{secrets.TF_VAR_tailscale_client_id}} --set-string oauth.clientSecret=${{secrets.TF_VAR_tailscale_client_secret}} --set-string apiServerProxyConfig.mode=true --wait"

      - name: Logout of Azure
        run: az logout